//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 08:30:56 PM IST 
//


package com.athena.airlines.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnonymousTravelerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnonymousTravelerType">
 *   &lt;complexContent>
 *     &lt;extension base="{}TravelerCoreType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnonymousTravelerType")
public class AnonymousTravelerType
    extends TravelerCoreType
{

    @XmlElement(name = "Name", required = true)
    protected TravelerSummaryType.Name name;
    
    @XmlElement(name = "Gender")
    protected TravelerDetailType.Gender gender;

	public TravelerSummaryType.Name getName() {
		return name;
	}

	public void setName(TravelerSummaryType.Name name) {
		this.name = name;
	}

	public TravelerDetailType.Gender getGender() {
		return gender;
	}

	public void setGender(TravelerDetailType.Gender gender) {
		this.gender = gender;
	}

}
