//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 08:30:56 PM IST 
//


package com.athena.airlines.dto;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CoreQuery">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OriginDestinations" type="{}AirShopReqAttributeQueryType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Preference" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AirlinePreferences" type="{}AirlinePreferencesType" minOccurs="0"/>
 *                   &lt;element name="CabinPreferences" type="{}CabinPreferencesType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataLists" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PassengerList" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Passenger" type="{}PassengerType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ContactList" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ContactInformation" type="{}ContactInformationType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Travelers"/>
 *         &lt;element name="Given" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coreQuery",
    "preference",
    "dataLists",
    "travelers",
    "aliases",
    "ptc",
    "mainPassengerName",
    "travelerDetailType",
    "recognizedTravelerMap",
    "customObjectsMap",
    "customStringMap",
    "integerIntegerMap",
    "integerStringMap",
    "stringIntegerMap",
    "enumsMap",
    "given"
})
@XmlRootElement(name = "AthenaAirlinePassenger")
public class AthenaAirlinePassenger {

    @XmlElement(name = "CoreQuery", required = true)
    protected AthenaAirlinePassenger.CoreQuery coreQuery;
    @XmlElement(name = "Preference")
    protected AthenaAirlinePassenger.Preference preference;
    @XmlElement(name = "DataLists")
    protected AthenaAirlinePassenger.DataLists dataLists;
    @XmlElement(name = "Travelers", required = true)
    protected Travelers travelers;
    @XmlElement(name = "Given")
    protected List<String> given;
    @XmlElement(name = "PTC")
    protected TravelerCoreType.PTC[] ptc;
    @XmlElement(name = "MainPassengerName")
    protected String mainPassengerName;
    @XmlElement(name = "TravelerDetailType")
    protected TravelerDetailType travelerDetailType;

    @XmlElement(name = "RecognizedTravelerMap")
    protected Map<String, TravelerDetailType> recognizedTravelerMap;

    @XmlElement(name = "CustomObjectsMap")
    protected Map<AnonymousTravelerType, TravelerDetailType> customObjectsMap;

    @XmlElement(name = "CustomStringMap")
    protected Map<TravelerDetailType, String> customStringMap;
	@XmlElement(name = "IntegerIntegerMap")
    protected Map<Integer, Integer> integerIntegerMap;
    @XmlElement(name = "IntegerStringMap")
    protected Map<Integer, String> integerStringMap;
    @XmlElement(name = "StringIntegerMap")
    protected Map<String, Integer> stringIntegerMap;
    @XmlElement(name = "EnumsMap")
    protected Map<TravelerGenderSimpleType, TravelerGenderSimpleType> enumsMap;
    @XmlElement(name = "Aliases")
    protected List<String> aliases;

    /**
     * Gets the value of the coreQuery property.
     * 
     * @return
     *     possible object is
     *     {@link AthenaAirlinePassenger.CoreQuery }
     *     
     */
    public AthenaAirlinePassenger.CoreQuery getCoreQuery() {
        return coreQuery;
    }

    /**
     * Sets the value of the coreQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link AthenaAirlinePassenger.CoreQuery }
     *     
     */
    public void setCoreQuery(AthenaAirlinePassenger.CoreQuery value) {
        this.coreQuery = value;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link AthenaAirlinePassenger.Preference }
     *     
     */
    public AthenaAirlinePassenger.Preference getPreference() {
        return preference;
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AthenaAirlinePassenger.Preference }
     *     
     */
    public void setPreference(AthenaAirlinePassenger.Preference value) {
        this.preference = value;
    }

    /**
     * Gets the value of the dataLists property.
     * 
     * @return
     *     possible object is
     *     {@link AthenaAirlinePassenger.DataLists }
     *     
     */
    public AthenaAirlinePassenger.DataLists getDataLists() {
        return dataLists;
    }

    /**
     * Sets the value of the dataLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link AthenaAirlinePassenger.DataLists }
     *     
     */
    public void setDataLists(AthenaAirlinePassenger.DataLists value) {
        this.dataLists = value;
    }

    /**
     * Gets the value of the travelers property.
     * 
     * @return
     *     possible object is
     *     {@link Travelers }
     *     
     */
    public Travelers getTravelers() {
        return travelers;
    }

    /**
     * Sets the value of the travelers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Travelers }
     *     
     */
    public void setTravelers(Travelers value) {
        this.travelers = value;
    }

    public List<String> getAliases() {
		return aliases;
	}

	public void setAliases(List<String> aliases) {
		this.aliases = aliases;
	}

	/**
     * Gets the value of the given property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the given property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGiven().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */

	public TravelerCoreType.PTC[] getPtc() {
		return ptc;
	}

	public void setPtc(TravelerCoreType.PTC[] ptc) {
		this.ptc = ptc;
	}

	public String getMainPassengerName() {
		return mainPassengerName;
	}

	public void setMainPassengerName(String mainPassengerName) {
		this.mainPassengerName = mainPassengerName;
	}

    public TravelerDetailType getTravelerDetailType() {
		return travelerDetailType;
	}

	public void setTravelerDetailType(TravelerDetailType travelerDetailType) {
		this.travelerDetailType = travelerDetailType;
	}

	public Map<String, TravelerDetailType> getRecognizedTravelerMap() {
		return recognizedTravelerMap;
	}

	public void setRecognizedTravelerMap(Map<String, TravelerDetailType> recognizedTravelerMap) {
		this.recognizedTravelerMap = recognizedTravelerMap;
	}

	public Map<AnonymousTravelerType, TravelerDetailType> getCustomObjectsMap() {
		return customObjectsMap;
	}

	public void setCustomObjectsMap(Map<AnonymousTravelerType, TravelerDetailType> customObjectsMap) {
		this.customObjectsMap = customObjectsMap;
	}

	public Map<TravelerDetailType, String> getCustomStringMap() {
		return customStringMap;
	}

	public void setCustomStringMap(Map<TravelerDetailType, String> customStringMap) {
		this.customStringMap = customStringMap;
	}

	public Map<Integer, Integer> getIntegerIntegerMap() {
		return integerIntegerMap;
	}

	public void setIntegerIntegerMap(Map<Integer, Integer> integerIntegerMap) {
		this.integerIntegerMap = integerIntegerMap;
	}

	public Map<Integer, String> getIntegerStringMap() {
		return integerStringMap;
	}

	public void setIntegerStringMap(Map<Integer, String> integerStringMap) {
		this.integerStringMap = integerStringMap;
	}

	public Map<String, Integer> getStringIntegerMap() {
		return stringIntegerMap;
	}

	public void setStringIntegerMap(Map<String, Integer> stringIntegerMap) {
		this.stringIntegerMap = stringIntegerMap;
	}

	public Map<TravelerGenderSimpleType, TravelerGenderSimpleType> getEnumsMap() {
		return enumsMap;
	}

	public void setEnumsMap(Map<TravelerGenderSimpleType, TravelerGenderSimpleType> enumsMap) {
		this.enumsMap = enumsMap;
	}

	public List<String> getGiven() {
		return given;
	}

	public void setGiven(List<String> given) {
		this.given = given;
	}

	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OriginDestinations" type="{}AirShopReqAttributeQueryType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originDestinations"
    })
    public static class CoreQuery {

        @XmlElement(name = "OriginDestinations")
        protected AirShopReqAttributeQueryType originDestinations;

        /**
         * Gets the value of the originDestinations property.
         * 
         * @return
         *     possible object is
         *     {@link AirShopReqAttributeQueryType }
         *     
         */
        public AirShopReqAttributeQueryType getOriginDestinations() {
            return originDestinations;
        }

        /**
         * Sets the value of the originDestinations property.
         * 
         * @param value
         *     allowed object is
         *     {@link AirShopReqAttributeQueryType }
         *     
         */
        public void setOriginDestinations(AirShopReqAttributeQueryType value) {
            this.originDestinations = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PassengerList" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Passenger" type="{}PassengerType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ContactList" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ContactInformation" type="{}ContactInformationType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passengerList",
        "contactList"
    })
    public static class DataLists {

        @XmlElement(name = "PassengerList")
        protected AthenaAirlinePassenger.DataLists.PassengerList passengerList;
        @XmlElement(name = "ContactList")
        protected AthenaAirlinePassenger.DataLists.ContactList contactList;

        /**
         * Gets the value of the passengerList property.
         * 
         * @return
         *     possible object is
         *     {@link AthenaAirlinePassenger.DataLists.PassengerList }
         *     
         */
        public AthenaAirlinePassenger.DataLists.PassengerList getPassengerList() {
            return passengerList;
        }

        /**
         * Sets the value of the passengerList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AthenaAirlinePassenger.DataLists.PassengerList }
         *     
         */
        public void setPassengerList(AthenaAirlinePassenger.DataLists.PassengerList value) {
            this.passengerList = value;
        }

        /**
         * Gets the value of the contactList property.
         * 
         * @return
         *     possible object is
         *     {@link AthenaAirlinePassenger.DataLists.ContactList }
         *     
         */
        public AthenaAirlinePassenger.DataLists.ContactList getContactList() {
            return contactList;
        }

        /**
         * Sets the value of the contactList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AthenaAirlinePassenger.DataLists.ContactList }
         *     
         */
        public void setContactList(AthenaAirlinePassenger.DataLists.ContactList value) {
            this.contactList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ContactInformation" type="{}ContactInformationType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contactInformation"
        })
        public static class ContactList {

            @XmlElement(name = "ContactInformation", required = true)
            protected List<ContactInformationType> contactInformation;

            /**
             * Gets the value of the contactInformation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the contactInformation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContactInformation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ContactInformationType }
             * 
             * 
             */
            public List<ContactInformationType> getContactInformation() {
                if (contactInformation == null) {
                    contactInformation = new ArrayList<ContactInformationType>();
                }
                return this.contactInformation;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Passenger" type="{}PassengerType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "passenger"
        })
        public static class PassengerList {

            @XmlElement(name = "Passenger", required = true)
            protected List<PassengerType> passenger;

            /**
             * Gets the value of the passenger property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the passenger property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPassenger().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PassengerType }
             * 
             * 
             */
            public List<PassengerType> getPassenger() {
                if (passenger == null) {
                    passenger = new ArrayList<PassengerType>();
                }
                return this.passenger;
            }

			public void setPassenger(List<PassengerType> passenger) {
				this.passenger = passenger;
			}

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AirlinePreferences" type="{}AirlinePreferencesType" minOccurs="0"/>
     *         &lt;element name="CabinPreferences" type="{}CabinPreferencesType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "airlinePreferences",
        "cabinPreferences"
    })
    public static class Preference {

        @XmlElement(name = "AirlinePreferences")
        protected AirlinePreferencesType airlinePreferences;
        @XmlElement(name = "CabinPreferences")
        protected CabinPreferencesType cabinPreferences;

        /**
         * Gets the value of the airlinePreferences property.
         * 
         * @return
         *     possible object is
         *     {@link AirlinePreferencesType }
         *     
         */
        public AirlinePreferencesType getAirlinePreferences() {
            return airlinePreferences;
        }

        /**
         * Sets the value of the airlinePreferences property.
         * 
         * @param value
         *     allowed object is
         *     {@link AirlinePreferencesType }
         *     
         */
        public void setAirlinePreferences(AirlinePreferencesType value) {
            this.airlinePreferences = value;
        }

        /**
         * Gets the value of the cabinPreferences property.
         * 
         * @return
         *     possible object is
         *     {@link CabinPreferencesType }
         *     
         */
        public CabinPreferencesType getCabinPreferences() {
            return cabinPreferences;
        }

        /**
         * Sets the value of the cabinPreferences property.
         * 
         * @param value
         *     allowed object is
         *     {@link CabinPreferencesType }
         *     
         */
        public void setCabinPreferences(CabinPreferencesType value) {
            this.cabinPreferences = value;
        }

    }

}
