//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.24 at 10:30:53 PM IST 
//


package com.kronos.airlines.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kronos.airlines.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AirlineID_QNAME = new QName("", "AirlineID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kronos.airlines.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Contacts }
     * 
     */
    public Contacts createContacts() {
        return new Contacts();
    }

    /**
     * Create an instance of {@link FlightDepartureType }
     * 
     */
    public FlightDepartureType createFlightDepartureType() {
        return new FlightDepartureType();
    }

    /**
     * Create an instance of {@link KronosAirlinePassenger }
     * 
     */
    public KronosAirlinePassenger createKronosAirlinePassenger() {
        return new KronosAirlinePassenger();
    }

    /**
     * Create an instance of {@link Travelers }
     * 
     */
    public Travelers createTravelers() {
        return new Travelers();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link TravelerFQTVType }
     * 
     */
    public TravelerFQTVType createTravelerFQTVType() {
        return new TravelerFQTVType();
    }

    /**
     * Create an instance of {@link TravelerFQTVType.Account }
     * 
     */
    public TravelerFQTVType.Account createTravelerFQTVTypeAccount() {
        return new TravelerFQTVType.Account();
    }

    /**
     * Create an instance of {@link TravelerCoreType }
     * 
     */
    public TravelerCoreType createTravelerCoreType() {
        return new TravelerCoreType();
    }

    /**
     * Create an instance of {@link TravelerSummaryType }
     * 
     */
    public TravelerSummaryType createTravelerSummaryType() {
        return new TravelerSummaryType();
    }

    /**
     * Create an instance of {@link TravelerDetailType }
     * 
     */
    public TravelerDetailType createTravelerDetailType() {
        return new TravelerDetailType();
    }

    /**
     * Create an instance of {@link TravelerSummaryType.Name }
     * 
     */
    public TravelerSummaryType.Name createTravelerSummaryTypeName() {
        return new TravelerSummaryType.Name();
    }

    /**
     * Create an instance of {@link TravelerCoreType.Age }
     * 
     */
    public TravelerCoreType.Age createTravelerCoreTypeAge() {
        return new TravelerCoreType.Age();
    }

    /**
     * Create an instance of {@link AirlinePreferencesType }
     * 
     */
    public AirlinePreferencesType createAirlinePreferencesType() {
        return new AirlinePreferencesType();
    }

    /**
     * Create an instance of {@link FlightArrivalType }
     * 
     */
    public FlightArrivalType createFlightArrivalType() {
        return new FlightArrivalType();
    }

    /**
     * Create an instance of {@link AirShopReqAttributeQueryType }
     * 
     */
    public AirShopReqAttributeQueryType createAirShopReqAttributeQueryType() {
        return new AirShopReqAttributeQueryType();
    }

    /**
     * Create an instance of {@link ContactInformationType }
     * 
     */
    public ContactInformationType createContactInformationType() {
        return new ContactInformationType();
    }

    /**
     * Create an instance of {@link Travelers.Traveler }
     * 
     */
    public Travelers.Traveler createTravelersTraveler() {
        return new Travelers.Traveler();
    }

    /**
     * Create an instance of {@link KronosAirlinePassenger.DataLists }
     * 
     */
    public KronosAirlinePassenger.DataLists createKronosAirlinePassengerDataLists() {
        return new KronosAirlinePassenger.DataLists();
    }

    /**
     * Create an instance of {@link Contacts.Contact }
     * 
     */
    public Contacts.Contact createContactsContact() {
        return new Contacts.Contact();
    }

    /**
     * Create an instance of {@link Contacts.Contact.Name }
     * 
     */
    public Contacts.Contact.Name createContactsContactName() {
        return new Contacts.Contact.Name();
    }

    /**
     * Create an instance of {@link CabinType }
     * 
     */
    public CabinType createCabinType() {
        return new CabinType();
    }

    /**
     * Create an instance of {@link CodesetType }
     * 
     */
    public CodesetType createCodesetType() {
        return new CodesetType();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link CountryCodeType }
     * 
     */
    public CountryCodeType createCountryCodeType() {
        return new CountryCodeType();
    }

    /**
     * Create an instance of {@link Departure }
     * 
     */
    public Departure createDeparture() {
        return new Departure();
    }

    /**
     * Create an instance of {@link FlightDepartureType.AirportCode }
     * 
     */
    public FlightDepartureType.AirportCode createFlightDepartureTypeAirportCode() {
        return new FlightDepartureType.AirportCode();
    }

    /**
     * Create an instance of {@link FlightDepartureType.Terminal }
     * 
     */
    public FlightDepartureType.Terminal createFlightDepartureTypeTerminal() {
        return new FlightDepartureType.Terminal();
    }

    /**
     * Create an instance of {@link KronosAirlinePassenger.CoreQuery }
     * 
     */
    public KronosAirlinePassenger.CoreQuery createKronosAirlinePassengerCoreQuery() {
        return new KronosAirlinePassenger.CoreQuery();
    }

    /**
     * Create an instance of {@link KronosAirlinePassenger.Preference }
     * 
     */
    public KronosAirlinePassenger.Preference createKronosAirlinePassengerPreference() {
        return new KronosAirlinePassenger.Preference();
    }

    /**
     * Create an instance of {@link CabinPreferencesType }
     * 
     */
    public CabinPreferencesType createCabinPreferencesType() {
        return new CabinPreferencesType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link EmailAddressType }
     * 
     */
    public EmailAddressType createEmailAddressType() {
        return new EmailAddressType();
    }

    /**
     * Create an instance of {@link PhoneTypeAIDM }
     * 
     */
    public PhoneTypeAIDM createPhoneTypeAIDM() {
        return new PhoneTypeAIDM();
    }

    /**
     * Create an instance of {@link IndividualType }
     * 
     */
    public IndividualType createIndividualType() {
        return new IndividualType();
    }

    /**
     * Create an instance of {@link PassengerType }
     * 
     */
    public PassengerType createPassengerType() {
        return new PassengerType();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link IdentityDocumentType }
     * 
     */
    public IdentityDocumentType createIdentityDocumentType() {
        return new IdentityDocumentType();
    }

    /**
     * Create an instance of {@link VisaType }
     * 
     */
    public VisaType createVisaType() {
        return new VisaType();
    }

    /**
     * Create an instance of {@link LanguageUsageType }
     * 
     */
    public LanguageUsageType createLanguageUsageType() {
        return new LanguageUsageType();
    }

    /**
     * Create an instance of {@link AnonymousTravelerType }
     * 
     */
    public AnonymousTravelerType createAnonymousTravelerType() {
        return new AnonymousTravelerType();
    }

    /**
     * Create an instance of {@link AddressContactType }
     * 
     */
    public AddressContactType createAddressContactType() {
        return new AddressContactType();
    }

    /**
     * Create an instance of {@link StructuredAddrType }
     * 
     */
    public StructuredAddrType createStructuredAddrType() {
        return new StructuredAddrType();
    }

    /**
     * Create an instance of {@link EmailIDType }
     * 
     */
    public EmailIDType createEmailIDType() {
        return new EmailIDType();
    }

    /**
     * Create an instance of {@link PhoneContactType }
     * 
     */
    public PhoneContactType createPhoneContactType() {
        return new PhoneContactType();
    }

    /**
     * Create an instance of {@link PhoneType.Number }
     * 
     */
    public PhoneType.Number createPhoneTypeNumber() {
        return new PhoneType.Number();
    }

    /**
     * Create an instance of {@link EmailType.Address }
     * 
     */
    public EmailType.Address createEmailTypeAddress() {
        return new EmailType.Address();
    }

    /**
     * Create an instance of {@link TravelerFQTVType.Account.SignInID }
     * 
     */
    public TravelerFQTVType.Account.SignInID createTravelerFQTVTypeAccountSignInID() {
        return new TravelerFQTVType.Account.SignInID();
    }

    /**
     * Create an instance of {@link TravelerFQTVType.Account.Number }
     * 
     */
    public TravelerFQTVType.Account.Number createTravelerFQTVTypeAccountNumber() {
        return new TravelerFQTVType.Account.Number();
    }

    /**
     * Create an instance of {@link TravelerCoreType.PTC }
     * 
     */
    public TravelerCoreType.PTC createTravelerCoreTypePTC() {
        return new TravelerCoreType.PTC();
    }

    /**
     * Create an instance of {@link TravelerSummaryType.ProfileID }
     * 
     */
    public TravelerSummaryType.ProfileID createTravelerSummaryTypeProfileID() {
        return new TravelerSummaryType.ProfileID();
    }

    /**
     * Create an instance of {@link TravelerDetailType.Gender }
     * 
     */
    public TravelerDetailType.Gender createTravelerDetailTypeGender() {
        return new TravelerDetailType.Gender();
    }

    /**
     * Create an instance of {@link TravelerSummaryType.Name.Surname }
     * 
     */
    public TravelerSummaryType.Name.Surname createTravelerSummaryTypeNameSurname() {
        return new TravelerSummaryType.Name.Surname();
    }

    /**
     * Create an instance of {@link TravelerSummaryType.Name.Given }
     * 
     */
    public TravelerSummaryType.Name.Given createTravelerSummaryTypeNameGiven() {
        return new TravelerSummaryType.Name.Given();
    }

    /**
     * Create an instance of {@link TravelerSummaryType.Name.Middle }
     * 
     */
    public TravelerSummaryType.Name.Middle createTravelerSummaryTypeNameMiddle() {
        return new TravelerSummaryType.Name.Middle();
    }

    /**
     * Create an instance of {@link TravelerCoreType.Age.BirthDate }
     * 
     */
    public TravelerCoreType.Age.BirthDate createTravelerCoreTypeAgeBirthDate() {
        return new TravelerCoreType.Age.BirthDate();
    }

    /**
     * Create an instance of {@link AirlinePreferencesType.Airline }
     * 
     */
    public AirlinePreferencesType.Airline createAirlinePreferencesTypeAirline() {
        return new AirlinePreferencesType.Airline();
    }

    /**
     * Create an instance of {@link FlightArrivalType.AirportCode }
     * 
     */
    public FlightArrivalType.AirportCode createFlightArrivalTypeAirportCode() {
        return new FlightArrivalType.AirportCode();
    }

    /**
     * Create an instance of {@link FlightArrivalType.Terminal }
     * 
     */
    public FlightArrivalType.Terminal createFlightArrivalTypeTerminal() {
        return new FlightArrivalType.Terminal();
    }

    /**
     * Create an instance of {@link AirShopReqAttributeQueryType.OriginDestination }
     * 
     */
    public AirShopReqAttributeQueryType.OriginDestination createAirShopReqAttributeQueryTypeOriginDestination() {
        return new AirShopReqAttributeQueryType.OriginDestination();
    }

    /**
     * Create an instance of {@link ContactInformationType.ContactProvided }
     * 
     */
    public ContactInformationType.ContactProvided createContactInformationTypeContactProvided() {
        return new ContactInformationType.ContactProvided();
    }

    /**
     * Create an instance of {@link KronosAirlinePassenger.DataLists.PassengerList }
     * 
     */
    public KronosAirlinePassenger.DataLists.PassengerList createKronosAirlinePassengerDataListsPassengerList() {
        return new KronosAirlinePassenger.DataLists.PassengerList();
    }

    /**
     * Create an instance of {@link KronosAirlinePassenger.DataLists.ContactList }
     * 
     */
    public KronosAirlinePassenger.DataLists.ContactList createKronosAirlinePassengerDataListsContactList() {
        return new KronosAirlinePassenger.DataLists.ContactList();
    }

    /**
     * Create an instance of {@link Contacts.Contact.Name.Surname }
     * 
     */
    public Contacts.Contact.Name.Surname createContactsContactNameSurname() {
        return new Contacts.Contact.Name.Surname();
    }

    /**
     * Create an instance of {@link Contacts.Contact.Name.Given }
     * 
     */
    public Contacts.Contact.Name.Given createContactsContactNameGiven() {
        return new Contacts.Contact.Name.Given();
    }

    /**
     * Create an instance of {@link Contacts.Contact.Name.Middle }
     * 
     */
    public Contacts.Contact.Name.Middle createContactsContactNameMiddle() {
        return new Contacts.Contact.Name.Middle();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "AirlineID")
    public JAXBElement<String> createAirlineID(String value) {
        return new JAXBElement<String>(_AirlineID_QNAME, String.class, null, value);
    }

}
